const studiedCourses = [
    {
        courses: [
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
            {
                code: "CS101",
                title: "Introduction to Programming",
                crHrs: 3,
                teacherName: "Teacher Name",
                teacherGrad: "Teacher Graduation",
                teacherUni: "Teacher University",
            },
        ],
    },
];

export default studiedCourses